-- =========================================================
--  Script de Bootstrap del Proyecto
--  Fecha: lunes-noviembre-03-2025
-- =========================================================

-- [1] Creación de Tablespaces

-- Creación del Tablespace de Datos principal
CREATE TABLESPACE "DATA"
DATAFILE 'C:\app\oracle\oradata\PROYECTOBD2\data01.dbf'
SIZE 500M
AUTOEXTEND ON
NEXT 100M
MAXSIZE 10G
EXTENT MANAGEMENT LOCAL
AUTOALLOCATE;
/

-- Creación del Tablespace Temporal
CREATE TEMPORARY TABLESPACE "TEMP"
TEMPFILE 'C:\app\oracle\oradata\PROYECTOBD2\temp01.dbf'
SIZE 200M
AUTOEXTEND ON
NEXT 50M
MAXSIZE 2G
EXTENT MANAGEMENT LOCAL;
/

-- [2] Creación de Roles

-- Rol para que devs creen en SUS propios esquemas
CREATE ROLE "DEV_FULL";
/
GRANT CREATE TABLE, CREATE VIEW, CREATE SEQUENCE,
CREATE PROCEDURE, CREATE TRIGGER, CREATE TYPE TO "DEV_FULL";
/

-- Roles para la aplicación (lectura y escritura)
CREATE ROLE "APP_RO";
/
CREATE ROLE "APP_RW";
/
-- NOTA: Los permisos de objeto para APP_RO (SELECT) y APP_RW (INSERT, UPDATE)
-- se otorgan en los scripts de creación de tablas.

-- [3] Creación de Usuarios

-- Usuario principal, dueño de los objetos (tablas, etc.)
CREATE USER "APP_OWNER" IDENTIFIED BY "ClaveFuerte!2025"
DEFAULT TABLESPACE "DATA"
TEMPORARY TABLESPACE "TEMP"
QUOTA UNLIMITED ON "DATA"
ACCOUNT UNLOCK;
/

-- Permisos base para el Owner
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE,
CREATE PROCEDURE, CREATE TRIGGER, CREATE TYPE TO "APP_OWNER";
/

-- Usuarios de desarrollo (con cuota de 2G en DATA)
CREATE USER "AXEL"     IDENTIFIED BY "ClaveFuerte1" DEFAULT TABLESPACE "DATA" TEMPORARY TABLESPACE "TEMP" QUOTA 2G ON "DATA" ACCOUNT UNLOCK;
/
CREATE USER "MARCO"    IDENTIFIED BY "ClaveFuerte1" DEFAULT TABLESPACE "DATA" TEMPORARY TABLESPACE "TEMP" QUOTA 2G ON "DATA" ACCOUNT UNLOCK;
/
CREATE USER "BRICKZON" IDENTIFIED BY "ClaveFuerte1" DEFAULT TABLESPACE "DATA" TEMPORARY TABLESPACE "TEMP" QUOTA 2G ON "DATA" ACCOUNT UNLOCK;
/
CREATE USER "COWAL"    IDENTIFIED BY "ClaveFuerte1" DEFAULT TABLESPACE "DATA" TEMPORARY TABLESPACE "TEMP" QUOTA 2G ON "DATA" ACCOUNT UNLOCK;
/
CREATE USER "ALDANA"   IDENTIFIED BY "ClaveFuerte1" DEFAULT TABLESPACE "DATA" TEMPORARY TABLESPACE "TEMP" QUOTA 2G ON "DATA" ACCOUNT UNLOCK;
/
CREATE USER "ANGEL"    IDENTIFIED BY "ClaveFuerte1" DEFAULT TABLESPACE "DATA" TEMPORARY TABLESPACE "TEMP" QUOTA 2G ON "DATA" ACCOUNT UNLOCK;
/
CREATE USER "LITA"     IDENTIFIED BY "ClaveFuerte1" DEFAULT TABLESPACE "DATA" TEMPORARY TABLESPACE "TEMP" QUOTA 2G ON "DATA" ACCOUNT UNLOCK;
/
CREATE USER "GABRIEL"  IDENTIFIED BY "ClaveFuerte1" DEFAULT TABLESPACE "DATA" TEMPORARY TABLESPACE "TEMP" QUOTA 2G ON "DATA" ACCOUNT UNLOCK;
/

-- [4] Permisos de Sistema (Grants)

-- Permiso básico de conexión para todos los desarrolladores
GRANT CREATE SESSION TO
"AXEL", "MARCO", "BRICKZON", "COWAL", "ALDANA", "ANGEL", "LITA", "GABRIEL";
/

-- [5] Autenticación Proxy (Permiso clave)

-- Permite a cada dev conectarse como dev[APP_OWNER] y actuar como APP_OWNER.

ALTER USER "APP_OWNER" GRANT CONNECT THROUGH "AXEL";
/
ALTER USER "APP_OWNER" GRANT CONNECT THROUGH "MARCO";
/
ALTER USER "APP_OWNER" GRANT CONNECT THROUGH "BRICKZON";
/
ALTER USER "APP_OWNER" GRANT CONNECT THROUGH "COWAL";
/
ALTER USER "APP_OWNER" GRANT CONNECT THROUGH "ALDANA";
/
ALTER USER "APP_OWNER" GRANT CONNECT THROUGH "ANGEL";
/
ALTER USER "APP_OWNER" GRANT CONNECT THROUGH "LITA";
/
ALTER USER "APP_OWNER" GRANT CONNECT THROUGH "GABRIEL";
/

-- =========================================================
--  FIN DEL SCRIPT
-- =========================================================